@host=3056
@url_dev=http://localhost:{{host}}/v1/api

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 

{
  "name" : "vuongadmin",
  "email" : "vuongadmin@test.com",
  "password" : "quocvuong42"
}